version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: gym_api_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: gym_api
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - gym_network

  app:
    build: .
    container_name: gym_api_app
    restart: unless-stopped
    ports:
      - '3333:3333'
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/gym_api?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - gym_network

volumes:
  mongodb_data:

networks:
  gym_network:
    driver: bridge
